1026~10816
ps-kjj/acmicpc.net pull request #16
Opened 2022-10-25 05:57 UTC by dev-Rluan

2022-10-31 07:49 UTC, tiger1710 requested changes
`jjr/boj9012.java` 파일 수정필요할거 같은데?.. 괄호문제 아니고 다른문제 푼거 올린듯..!

2022-10-31 07:49 UTC, tiger1710 commented on jjr/boj10816.java
> +            if(map.containsKey(nt)){
`https://www.geeksforgeeks.org/hashmap-putifabsentkey-value-method-in-java-with-examples/`

아마 이런거 많을꺼야 map이나 set 사용할때..!

put if else default인가 도 있을거야 한번 봐바

2022-10-31 10:08 UTC, dev-Rluan commented on jjr/boj10816.java
> +            if(map.containsKey(nt)){
ㄳㄳ 처음알았네

2022-11-01 00:38 UTC, tiger1710 approved these changes
LGTM

2022-11-01 00:39 UTC, merged